services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    ports:
      - "11300:11300"

  redis_rdb:
    image: redis:latest
    container_name: redis_rdb
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_rdb_data:/data

  redis_aof:
    image: redis:latest
    container_name: redis_aof
    command: redis-server --appendonly yes --loglevel warning
    ports:
      - "6380:6379"
    volumes:
      - redis_aof_data:/data

  queue_service:
    build: ./queue_service
    ports:
      - "3000:3000"
    depends_on:
      - beanstalkd
      - redis_rdb
      - redis_aof

volumes:
  redis_rdb_data:
  redis_aof_data:
